import type { Metadata } from "next";
import { Mulish, Alegreya } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";

const mulish = Mulish({
    subsets: ["latin"],
    variable: "--font-mulish",
});
const alegreya = Alegreya({
    subsets: ["latin"],
    variable: "--font-alegreya",
});

export const metadata: Metadata = {
    title: "Red Social Next App",
    description: "Generated by create next app",
};


export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${mulish.variable} ${alegreya.variable}`}>
            <body suppressHydrationWarning>                
                <Navbar></Navbar>
                {children}
            </body>
        </html>
    );
}
